# nixpacks.toml
[project]
name = "discord-waifu-bot"

[env]
PYTHON_VERSION = "3.10"

[phases.setup]
commands = [
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install -r requirements.txt"
]

[build]
command = "true"

[run]
# Changed to standard "bot.py"
command = "python bot.py"
